### ISSUE TITLE
Proxyquire not stubbing when called by `npm test`

### ISSUE THREAD

**Issue by Telokis** [thlorenz/proxyquire#161] opened 2017-04-22 17:57 UTC
Version: 1.7.11

I have this:

```js
const proxyquire = require('proxyquire').noPreserveCache();
let amie;

amie = proxyquire('../../', {
    'fs': null
});
```

If I call the file with `./node_modules/.bin/mocha test/caching.test/caching.test.js` it works pretty fine, an error is properly thrown.

But if I do `npm test`, the stubbing doesn't happen and `fs` is successfully loaded by my library.

**Comment by bendrucker** [comment] 2017-04-23 01:02
This is going to be incredibly difficult to track down without more information. It's pretty clear to me that this isn't a proxyquire bug/issue and more of a general support request. Happy to try to help if you have more info to post but for now I'll go ahead and close this out.

**Closed by bendrucker** 2017-04-23 01:02 UTC

**Comment by Telokis** [comment] 2017-04-23 12:41
Well I think this is a proxyquire related thing since everything else is behaving as expected.
I do not think this is a bug but rather a thing I'm doing wrong.
My first guess was that proxyquire is using the cached version of fs.

**Comment by thlorenz** [comment] 2017-04-23 13:01
OK, so it is some sort of support request then ...
We cannot help you unless we have a version of your code online with which we can reproduce your problem. Therefore please push something on github which shows the problem when we just do the following `npm install && npm test`.

That said we can't guarantee to help you even then since our time is limited as well and maintaining proxyquire is something we do on our own time ...

**Comment by Telokis** [comment] 2017-04-23 14:13
You can get it in the Amie repository in my profile. http://github.com/telokis/amie.
The test is in the file `test/caching.test/caching.test.js`. It is currently commented out because of travis. I'm on my phone but I'll try to update it quickly to match what I wrote above.

Thanks for helping me, I find this issue really odd since I'm not doing anything specifically particular.

**Comment by Telokis** [comment] 2017-04-23 14:36
@thlorenz Alright the repo is up to date with the original post.
The test should fail because fs is not found but fails for another reason

**Comment by Telokis** [comment] 2017-04-23 21:52
One strange thing is:
Doing `./node_modules/.bin/mocha test/caching.test/caching.test.js  test/basic.test/basic.test.js` triggers the not found error.
But doing `./node_modules/.bin/mocha test/basic.test/basic.test.js test/caching.test/caching.test.js` ignores the stub.

This has to be an issue with caching. Maybe mocha does stuff I don't know about? But why would I be the first one to experience this? I can't be the only one using Mocha and Proxyquire...

**Comment by bendrucker** [comment] 2017-04-23 23:58
The order thing is super important, that's the issue here.

You require your module via proxyquire in your `caching` test and mock-remove `fs`. Then in your `basic` you use a plain require. You'll just need to use `noPreserveCache` in your `caching` test. Otherwise you end up with your root module in the cache. You had that in your original example but I don't see it in the source.

**Comment by Telokis** [comment] 2017-04-24 11:43
@bendrucker Sorry, I forgot to put it back in the code I updated yesterday.
But with or without `noPreserveCache` the result is strictly the same.

**Comment by Telokis** [comment] 2017-04-26 06:19
@bendrucker @thlorenz Is this a *real* issue or did I misunderstand the purpose of `noPreserveCache`?

**Comment by Telokis** [comment] 2017-05-05 11:27
@bendrucker @thlorenz Could you, please, reopen this issue or answer me?

**Comment by bendrucker** [comment] 2017-05-05 15:14
Hey sorry I don't have time to pursue this further at the moment. Don't think Thorsten will either. If you can develop a failing test as a PR I could dig from there.
