### ISSUE TITLE
Question: How to get proxyquire work with classes?

### ISSUE THREAD

**Issue by 360disrupt** [thlorenz/proxyquire#136] opened 2016-09-23 12:56 UTC
I have a class `Trader` which I want to do some integration tests with. This class uses another class `Bitfinex` which uses a service for the rest api. I want to prevent this api to make real orders on an exchange.

```
proxyquire =  require('proxyquire').callThru() #take all methods which are not mocked
BitfinexApiStub = {}
Trader = proxyquire(applicationDir + 'backend/bitcoin/trader.class.js', './exchanges/bitfinex.class.js': {'bitfinex-api-node': BitfinexApiStub})

BitfinexApiStub.rest = ()->
  return {
    new_order: ()->
      console.log "new_order"
      return null
  }

```
## Class

```
class Bitfinex extends Bitcoin
  constructor: (options)->
    super(options)
    if options.apiKey? && options.apiSecret?
      @.bitfinexRestApi = new BitfinexApi(options.apiKey, options.apiSecret).rest
    return

  order: (order, callback)->
    ...

module.exports = Bitfinex
```
## Error

`TypeError: Bitfinex is not a constructor`

The error only occurs when I use proxyquire instead of require.
## Question

1) How can I mock that specific api call in the class `Bitfinex`?
2) Alternatively, how could I mock the method order of `Bitfinex`? Which would be also fine, but I'm getting the same error.

**Comment by bendrucker** [comment] 2016-09-23 13:56
Please create a repo with a minimally reproducible project that we can run via `npm install && npm test` to see the issue. Classes are really just functions so there's nothing special going on.

**Comment by 360disrupt** [comment] 2016-09-23 14:52
[MinimalBitcoin.zip](https://github.com/thlorenz/proxyquire/files/489956/MinimalBitcoin.zip)
Run 
`npm install`
`gulp testBE` to test, it will fail.
You can edit `MinimalBitcoin/src/backend/bitcoin/specs/trader.class.spec.coffee` line 11 & 12 to see that it does not file unless `proxyquire` is used.

**Comment by 360disrupt** [comment] 2016-09-23 16:33
[MinimalTest.zip](https://github.com/thlorenz/proxyquire/files/490194/MinimalTest.zip)
Ok I reduced it to
- 3 x src (I kept the file structure, trader -> bitfinex -> bitcoin (maybe it is relevant to the problem) 
- 1 x spec 
- 1 x gulp file
- 1 x package JSON  
Just run `npm install && gulp` in order to test. Uncomment l10-14 in `trader.class.spec` to cause the error.

**Comment by thlorenz** [comment] 2016-09-23 18:36
@bendrucker actually I also noticed something funny going on when using `class` and trying to `callThru`.
It doesn't seem to detect a function on a class when looking for stubbed out ones (i.e. if you use a `class` as a stub).

You could easily repro by trying to stub out path with:

```js
class Path {
  basname() { throw new Error('I am a good error cause it means proxyquire worked as expected') }
}
```
then using that to stub `path`.

LMK if you need help .. seems like the problem is in one of the underlying modules that looks for functions on `Object`s (not working properly for `class`es .. for `prototype`s it does).

**Comment by bendrucker** [comment] 2016-09-23 18:51
Ah nice, I'll dig deeper on classes and try to get a pure JS repro case going.

**Comment by bendrucker** [comment] 2016-09-23 19:53
Dug around a bit more. Found one fairly direct issue:

This isn't valid:

```js
Trader = proxyquire(applicationDir + 'trader.class.js', {
    './bitfinex.class.js': {
      'bitfinex-api-node': BitfinexApiStub
    }
  })
```

You can't do nesting like that. You're replacing your class with an object (`{'bitfinex-api-node': {}}`). You should avoid transitive module testing but if you need that you'll have to use the [`@global`](https://github.com/thlorenz/proxyquire#globally-override-require) feature.

**Comment by jasonrhodes** [comment] 2016-11-10 15:30
So just a +1 and some extra details here, turns out if you use an ES2015 JS `class` and don't use `noCallThru`, when the `fill-keys` lib does the merge using the `merge-descriptors` lib, it uses `hasOwnProperty.call` to check if the passed in mock has the method, which won't find instance methods. To support instance-based proxyquire mocks, would need to PR `merge-descriptors` or find a new way to do that process, it looks like. 

(Would `'methodName' in mock` work ok or would that be bad because of prototype walking?)

**Comment by bendrucker** [comment] 2016-11-10 16:42
Using in might be ok. Will happily review a PR to fill keys with tests.

**Comment by bendrucker** [comment] 2018-08-22 02:43
Closing this and #178—if you want full class support, enable `noCallThru`. If someone has a clever idea for how to handle this I'm all ears but I don't think it's a feasible/worthwhile goal for the lib right now.

**Closed by bendrucker** 2018-08-22 02:43 UTC

**Comment by JimTheMan** [comment] 2019-08-25 17:49
@bendrucker can you please explain how to use proxyquire with classes instead of closing this issue with no real solution? I am using `noCallThru`, but it still doesn't work. See https://github.com/thlorenz/proxyquire/issues/247. Thanks :)

**Comment by blmille1** [comment] 2021-03-12 16:54
Same here. I have a module that exports a class only with `module.exports = MyAwesomeClass`.  I'm having a hard time getting proxyquire to work with it.  Will you please add a test/sample that explicitly exports a class?

**Comment by bendrucker** [comment] 2021-03-12 19:27
See b5cfae6 for a simple illustration of how to make use of `@noCallThru` to ensure your prototypes are preserved when using the `class` keyword. This isn't specific to `class` and would apply equally if you defined a traditional constructor function and attached methods to its prototype. 

Please remember that issues are not a support forum and many of the issues that have been raised have had less to do with classes than calling proxyquire correctly (e.g. using its return value instead of expecting it to cause side effects). PRs to improve documentation and test coverage are always welcome, but requests to debug private code are not.

If you think you've encountered a bug or want to propose a feature/change, do go ahead and open an issue with a simple, generic reproduction.
